name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0ad0413e25f06ffd0faef14625fab422707ab54bd009b626e95a2d2d7a40c71"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
