name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13147bce104c6898b4abea62e0158033f6fadc3b0be1524ce1543cf433c810bc"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
