name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "064a92d3e7d16f03e982d8d62aa3f9dbcf1dbe47126d842ba008f0879f568cfb"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
