name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d39a8fd2f64e80072ebc7ffb54f2188fc427cde71f75c2873e9dff1111f44ae9"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
