name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68dbd5869fd821e703cb8d8b40546df51610ab19355615d77e55324a2a4217db"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
