name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d05b71633d04969188fc3b0e823f023cef5230f06e83a4d7b2895bdf49da7579"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
