name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d89c6a8a187fc5197c6de7fd9e540a63855dd7591f068ab6ddf670aa66eb4a0"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
