name = "Puppies' Delight"
author = "hotel & cypress"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "905e55160d581ac806554621152de10ac6d73b1ef9319b6a11fdc9f2903580b2"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
